name: Sync Panel to GitHub

on:
  workflow_dispatch:   # bisa dijalankan manual
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 🔍 Step 1: Debug - cek isi folder di panel
      - name: Debug - List files in /home/container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          script: |
            echo "=== LIST ISI FOLDER /home/container ==="
            ls -lah /home/container || echo "Folder tidak ditemukan"

      # 📥 Step 2: Download semua file dari panel
      - name: Download from Panel via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          source: "/home/container/*"
          target: "./panel-backup"

      # 💾 Step 3: Commit hasil ke GitHub
      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          cp -r ./panel-backup/* .
          git add .
          git commit -m "Auto Sync from Panel" || echo "No changes to commit"
          git push
